spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/commerce"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}